storage:
  type: LiteSQL # LiteSQL (local storage), MySQL, MariaDB, MongoDB
  host: "localhost"
  port: 3306
  database: "database_name"
  username: "root"
  password: ""
  save-delay: 300

general:
  delay-between-database-updates: 300
  use-action-bar-on-actions: true
  debug-messages: true
  use-calendar: false
  permission-plugin: auto # luckperms

locale:
  lang: en_EN
  decimal:display: 1
  title:
    fade-in: 1
    stay: 18
    fade-out: 2

map:
  update-delay: 5

team:
  default-relation: neutral
  none-color: "#CACACA"
  deploy-timer: 10
  deploy-cooldown: 120
  maximum-members: 50 #-1 for infinite

bossbar:
  color: # RED, YELLOW, BLUE, GREEN, PINK, PURPLE, WHITE
    neutral: WHITE # no team
    controlled: YELLOW # it's like neutral but controlled by a team
    team: BLUE
    ally: GREEN
    truce: PURPLE
    enemy: RED

dynmap:
  hide-by-default: false
  use-3d-region: false # bugued, keep it false
  dynmap-info-window: false
  tick-per-update: 20
  many-update-delay: 1
  fill-opacity: 80

battlefield:
  wednesday-bf:
    reset-team: true
    end-on-battle-end: true
    # announcements: false
    start:
      day: "monday"
      time: "18:00"
    end:
      day: "monday"
      time: "21:00"
    territory-types:
      - "headquarter-koth"
    territories: []