storage:
  type: LiteSQL # LiteSQL (local storage), MySQL, MariaDB, MongoDB
  host: "localhost"
  port: 3306
  database: "database_name"
  username: "root"
  password: ""
  save-delay: 300

general:
  delay-between-database-updates: 300
  use-action-bar-on-actions: true
  debug-messages: true
  use-calendar: false
  permission-plugin: auto # luckperms

locale:
  lang: en_EN
  decimal:display: 1
  title:
    fade-in: 1
    stay: 18
    fade-out: 2

map:
  update-delay: 5

empires:
  none-display: "&7No Empire"

team:
  #system: "nodewar"
  default-relation: neutral

bossbar:
  color: # RED, YELLOW, BLUE, GREEN, PINK, PURPLE, WHITE
    neutral: WHITE # no team
    controlled: YELLOW # it's like neutral but controlled by a team
    team: BLUE
    ally: GREEN
    truce: PURPLE
    enemy: RED

dynmap:
  layer-name: "Nodewar"
  hide-by-default: false
  use-3d-region: false
  dynmap-info-window: false
  tick-per-update: 20
  many-update-delay: 1
  fill-opacity: 50

calendar:
  wednesday-bf:
    start:
      day-name: wednesday
      system-time: "18:00"
      vulnerable: true
      empire: neutral
      worlds:
        Fodlan:
          territories:
            - "garreg-mach"
    end:
      day-name: wednesday
      system-time: "21:00"
      vulnerable: false
      worlds:
        Fodlan:
          territories:
            - "garreg-mach"
  friday-bf:
    start:
      day-name: friday
      system-time: "20:00"
      vulnerable: true
      empire: neutral
      worlds:
        Fodlan:
          territories:
            - "garreg-mach"
    end:
      day-name: friday
      system-time: "22:00"
      vulnerable: false
      worlds:
        Fodlan:
          territories:
            - "garreg-mach"
  sunday-bf:
    start:
      day-name: sunday
      system-time: "16:00"
      vulnerable: true
      empire: neutral
      worlds:
        Fodlan:
          territories:
            - "garreg-mach"
    end:
      day-name: sunday
      system-time: "20:00"
      vulnerable: false
      worlds:
        Fodlan:
          territories:
            - "garreg-mach"