storage:
  type: LiteSQL # LiteSQL (local storage), MySQL, MariaDB, MongoDB
  host: "localhost"
  port: 3306
  database: "database_name"
  username: "root"
  password: ""
  save-delay: 300

general:
  debug-messages: true
  permission-plugin: auto # luckperms and "auto". Ask dev to add others
  can-counter-attack: false # Can a team attack another territory from a territory already in battle

locale:
  lang: en_EN
  decimal-display: 1
  title:
    fade-in: 1
    stay: 18
    fade-out: 2

team:
  system: "auto" # "Towny", "UltimateClans", "nodewar" OR "auto"
  creation-cost: 0
  default-relation: neutral
  none-color: "#4C4C4C"
  deploy-timer: 10
  deploy-cooldown: 120
  maximum-members: 50 #-1 for infinite
  name-min-length: 5
  name-max-length: 11 # Maximum 33
  shortname-min-length: 3
  shortname-max-length: 5

bossbar:
  color: # RED, YELLOW, BLUE, GREEN, PINK, PURPLE, WHITE
    neutral: WHITE # no team
    controlled: YELLOW # it's like neutral but controlled by a team
    team: BLUE
    ally: GREEN
    truce: PURPLE
    enemy: RED

webmap:
  plugins: # "auto" to add use any compatible webmap plugin. add "!" before each line to remove the selected plugin.
    - "auto"
    # - "dynmap"
    # - "Squaremap"
    # - "bluemap"
  background-color: "#FFFFFF"
  simple-line: false
  line-thickness: 3
  hide-by-default: false
  use-3d-region: false
  tick-per-update: 20
  many-update-delay: 1
  fill-opacity: 80
  line-opacity: 90

battlefield:
  alerts:
    - "1h"
    - "30m"
    - "10m"
    - "5m"
    - "2m"
    - "1m"
    - "30s"
    - "10s"
    - "5s"
    - "4s"
    - "3s"
    - "2s"
    - "1s"
  list:
    # MONDAY
    monday-t1:
      display: "Monday Tier 1"
      from:
        day: monday
        time: '18:15'
      to:
        day: monday
        time: '19:00'
      reset-team: true
      end-battle-on-battlefield-end: true
      territory-types:
        - t1
        - cp-t1
    monday-t2:
      display: "Monday Tier 2"
      from:
        day: monday
        time: '19:15'
      to:
        day: monday
        time: '20:00'
      reset-team: true
      end-battle-on-battlefield-end: true
      territory-types:
        - t2
        - cp-t2
    monday-t3:
      display: "Monday Tier 3"
      from:
        day: monday
        time: '20:15'
      to:
        day: monday
        time: '21:00'
      reset-team: true
      end-battle-on-battlefield-end: true
      territory-types:
        - t3
        - cp-t3
    # WEDNESDAY
    wednesday-t1:
      display: "Wednesday Tier 1"
      from:
        day: wednesday
        time: '18:15'
      to:
        day: wednesday
        time: '19:00'
      reset-team: true
      end-battle-on-battlefield-end: true
      territory-types:
        - t1
        - cp-t1
    wednesday-t2:
      display: "Wednesday Tier 2"
      from:
        day: wednesday
        time: '19:15'
      to:
        day: wednesday
        time: '20:00'
      reset-team: true
      end-battle-on-battlefield-end: true
      territory-types:
        - t2
        - cp-t2
    wednesday-t3:
      display: "Wednesday Tier 3"
      from:
        day: wednesday
        time: '20:15'
      to:
        day: wednesday
        time: '21:00'
      reset-team: true
      end-battle-on-battlefield-end: true
      territory-types:
        - t3
        - cp-t3
    # SATURDAY
    saturday-t1:
      display: "Saturday Tier 1"
      from:
        day: saturday
        time: '16:15'
      to:
        day: saturday
        time: '17:00'
      reset-team: true
      end-battle-on-battlefield-end: true
      territory-types:
        - t1
        - cp-t1
    saturday-t2:
      display: "Saturday Tier 2"
      from:
        day: saturday
        time: '17:15'
      to:
        day: saturday
        time: '18:00'
      reset-team: true
      end-battle-on-battlefield-end: true
      territory-types:
        - t2
        - cp-t2
    saturday-t3:
      display: "Saturday Tier 3"
      from:
        day: saturday
        time: '18:15'
      to:
        day: saturday
        time: '19:00'
      reset-team: true
      end-battle-on-battlefield-end: true
      territory-types:
        - t3
        - cp-t3
