storage:
  type: LiteSQL # LiteSQL (local storage), MySQL, MariaDB, MongoDB
  host: "localhost"
  port: 3306
  database: "database_name"
  username: "root"
  password: ""
  save-delay: 300

general:
  lang: en_EN
  delay-between-database-updates: 300
  use-action-bar-on-actions: true
  debug-messages: true
  use-calendar: false

map:
  update-delay: 5

empires:
  none-display: "&7No Empire"

teams:
  default-relation: neutral

bossbar:
  color:
    neutral: WHITE #RED, YELLOW, BLUE, GREEN, PINK, PURPLE, WHITE
    team: BLUE
    ally: GREEN
    truce: PURPLE
    enemy: RED

calendar:
  wednesday-bf:
    start:
      day-name: wednesday
      system-time: "18:00"
      vulnerable: true
      empire: neutral
      worlds:
        Fodlan:
          territories:
            - "garreg-mach"
    end:
      day-name: wednesday
      system-time: "21:00"
      vulnerable: false
      worlds:
        Fodlan:
          territories:
            - "garreg-mach"
  friday-bf:
    start:
      day-name: friday
      system-time: "20:00"
      vulnerable: true
      empire: neutral
      worlds:
        Fodlan:
          territories:
            - "garreg-mach"
    end:
      day-name: friday
      system-time: "22:00"
      vulnerable: false
      worlds:
        Fodlan:
          territories:
            - "garreg-mach"
  sunday-bf:
    start:
      day-name: sunday
      system-time: "16:00"
      vulnerable: true
      empire: neutral
      worlds:
        Fodlan:
          territories:
            - "garreg-mach"
    end:
      day-name: sunday
      system-time: "20:00"
      vulnerable: false
      worlds:
        Fodlan:
          territories:
            - "garreg-mach"