storage:
  type: LiteSQL # LiteSQL (local storage), MySQL, MariaDB, MongoDB
  host: "localhost"
  port: 3306
  database: "database_name"
  username: "root"
  password: ""
  save-delay: 300

general:
  debug-messages: true
  permission-plugin: auto # luckperms

locale:
  lang: en_EN
  decimal-display: 1
  title:
    fade-in: 1
    stay: 18
    fade-out: 2

team:
  system: "Nodewar" # Nodewar, Towny
  creation-cost: 0
  default-relation: neutral
  none-color: "#4C4C4C"
  deploy-timer: 10
  deploy-cooldown: 120
  maximum-members: 50 #-1 for infinite
  name-min-length: 5
  name-max-length: 11 # Maximum 33
  shortname-min-length: 3
  shortname-max-length: 5

bossbar:
  color: # RED, YELLOW, BLUE, GREEN, PINK, PURPLE, WHITE
    neutral: WHITE # no team
    controlled: YELLOW # it's like neutral but controlled by a team
    team: BLUE
    ally: GREEN
    truce: PURPLE
    enemy: RED

dynmap:
  hide-by-default: false
  use-3d-region: false # bugued, keep it false
  dynmap-info-window: false
  tick-per-update: 20
  many-update-delay: 1
  fill-opacity: 80

battlefield:
  alerts:
    - "1h"
    - "30m"
    - "10m"
    - "5m"
    - "2m"
    - "1m"
    - "30s"
    - "10s"
    - "5s"
    - "4s"
    - "3s"
    - "2s"
    - "1s"
  list:
    monday-bf:
      display: "Monday's battlefield"
      reset-team: true
      end-battle-on-battlefield-end: true
      # announcements: false
      from:
        day: "monday"
        time: "18:00"
      to:
        day: "monday"
        time: "21:00"
      territory-types:
        - "headquarter-koth"
      territories: []