name: Nodewar
version: 1.0.1
description: Nodewar plugin
api-version: 1.13
author: Rosstail
website: https://www.spigotmc.org/resources/nodewar.98373/
depend:
  - WorldGuard
softdepend:
  - PlaceholderAPI
main: fr.rosstail.nodewar.Nodewar
commands:
  nodewar:
    description: Display default command
    usage: /nodewar
    permission-message: You don't have permission !
    permission: nodewar

permissions:
  nodewar:
    default: true