name: Nodewar
version: 1.3.0-beta
description: A persistent Worldguard based territory system
api-version: 1.15
author: Rosstail
website: https://www.spigotmc.org/resources/nodewar.98373/
depend:
  - WorldGuard
softdepend:
  - PlaceholderAPI
  - Dynmap
  - DynmapAPI
main: fr.rosstail.nodewar.Nodewar
commands:
  nodewar:
    description: Display default commands
    usage: /nodewar
    permission-message: You don't have permission !
    permission: nodewar

permissions:
  nodewar:
    default: true