name: Nodewar
version: ${project.version}
description: A persistent Worldguard based territory system
api-version: 1.15
author: Rosstail
website: https://www.spigotmc.org/resources/nodewar.98373/
depend:
  - WorldGuard
softdepend:
  - PlaceholderAPI
  - Dynmap
  - DynmapAPI
  - Luckperms
  - BlueMap
  - BlueMapAPI
main: fr.rosstail.nodewar.Nodewar
commands:
  nodewar:
    description: Display default commands
    usage: /nodewar
    permission-message: You don't have permission !
    permission: nodewar.command
    aliases: [nw]

permissions:
  nodewar:
    default: true

  nodewar.command:
    default: true

  nodewar.commmand.admin:
    default: op

  nodewar.command.team:
    default: true
  nodewar.command.team.check:
    default: true
  nodewar.command.team.create:
    default: true
  nodewar.command.team.deploy:
    default: true
  nodewar.command.team.join:
    default: true
  nodewar.command.team.leave:
    default: true
  nodewar.command.team.list:
    default: true
  nodewar.command.team.*:
    default: op
    children:
      nodewar.command.team: true
      nodewar.command.team.check: true
      nodewar.command.team.create: true
      nodewar.command.team.deploy: true
      nodewar.command.team.join: true
      nodewar.command.team.leave: true
      nodewar.command.team.invites.*: true
      nodewar.command.team.manage.*: true

  nodewar.command.team.invites:
    default: true
  nodewar.command.team.invites.check:
    default: true
  nodewar.command.team.invites.close:
    default: true
  nodewar.command.team.invites.open:
    default: true
  nodewar.command.team.invites.*:
    default: op
    children:
      nodewar.command.team.invites: true
      nodewar.command.team.invites.check: true
      nodewar.command.team.invites.close: true
      nodewar.command.team.invites.open: true

  nodewar.command.team.manage:
    default: true
  nodewar.command.team.manage.close:
    default: true
  nodewar.command.team.manage.color:
    default: true
  nodewar.command.team.manage.disband:
    default: true
  nodewar.command.team.manage.invite:
    default: true
  nodewar.command.team.manage.open:
    default: true
  nodewar.command.team.manage.*:
    default: op
    children:
      nodewar.command.team.manage: true
      nodewar.command.team.manage.close: true
      nodewar.command.team.manage.color: true
      nodewar.command.team.manage.disband: true
      nodewar.command.team.manage.invite: true
      nodewar.command.team.manage.open: true
      nodewar.command.team.manage.member.*: true
      nodewar.command.team.manage.relation.*: true

  nodewar.command.team.manage.member:
    default: true
  nodewar.command.team.manage.member.demote:
    default: true
  nodewar.command.team.manage.member.kick:
    default: true
  nodewar.command.team.manage.member.promote:
    default: true
  nodewar.command.team.manage.member.transfer:
    default: true
  nodewar.command.team.manage.member.*:
    default: op
    children:
      nodewar.command.team.manage.member: true
      nodewar.command.team.manage.member.demote: true
      nodewar.command.team.manage.member.kick: true
      nodewar.command.team.manage.member.promote: true
      nodewar.command.team.manage.member.transfer: true

  nodewar.command.team.manage.relation:
    default: true
  nodewar.command.team.manage.relation.accept:
    default: true
  nodewar.command.team.manage.relation.request:
    default: true
  nodewar.command.team.manage.relation.close:
    default: true
  nodewar.command.team.manage.relation.edit:
    default: true
  nodewar.command.team.manage.relation.invites:
    default: true
  nodewar.command.team.manage.relation.open:
    default: true
  nodewar.command.team.manage.relation.*:
    default: op
    children:
      nodewar.command.team.manage.relation: true
      nodewar.command.team.manage.relation.accept: true
      nodewar.command.team.manage.relation.request: true
      nodewar.command.team.manage.relation.close: true
      nodewar.command.team.manage.relation.edit: true
      nodewar.command.team.manage.relation.invites: true
      nodewar.command.team.manage.relation.open: true

  nodewar.command.territory:
    default: true
  nodewar.command.territory.check:
    default: true
  nodewar.command.territory.*:
    default: op
    children:
      nodewar.command.territory: true
      nodewar.command.territory.check: true

  nodewar.command.*:
    default: op
    children:
      nodewar.command: true
      nodewar.command.admin: true
      nodewar.command.team.*: true
      nodewar.command.territory.*: true

  nodewar.*:
    default: op
    children:
      nodewar.command.*: true