name: Nodewar
version: 1.3.0-beta
description: A persistent Worldguard based territory system
api-version: 1.15
author: Rosstail
website: https://www.spigotmc.org/resources/nodewar.98373/
depend:
  - WorldGuard
softdepend:
  - PlaceholderAPI
  - Dynmap
  - DynmapAPI
main: fr.rosstail.nodewar.Nodewar
commands:
  nodewar:
    description: Display default commands
    usage: /nodewar
    permission-message: You don't have permission !
    permission: nodewar.command

permissions:
  nodewar:
    default: true
  nodewar.command:
    default: true
  nodewar.command.*:
    default: false
    children:
      - nodewar.command.admin
      - nodewar.command.empire
      - nodewar.command.help
  nodewar.command.admin:
    default: op
  nodewar.command.admin.*:
    default: false
    children:
      - nodewar.command.admin.empire
      - nodewar.command.admin.player
      - nodewar.command.admin.territory
  nodewar.command.admin.empire:
    default: op
  nodewar.command.admin.empire.*:
    default: false
    children:
      - nodewar.command.admin.empire.create
      - nodewar.command.admin.empire.disband
      - nodewar.command.admin.empire.edit
  nodewar.command.admin.empire.create:
    default: op
  nodewar.command.admin.empire.disband:
    default: op
  nodewar.command.admin.empire.edit:
    default: op
  nodewar.command.admin.empire.edit.*:
    default: false
    children:
      - nodewar.command.admin.empire.edit.bossbarcolor
      - nodewar.command.admin.empire.edit.color
      - nodewar.command.admin.empire.edit.display
      - nodewar.command.admin.empire.edit.friendlyfire
  nodewar.command.admin.empire.edit.display:
    default: op
  nodewar.command.admin.empire.edit.color:
    default: op
  nodewar.command.admin.empire.edit.bossbarcolor:
    default: op
  nodewar.command.admin.empire.edit.friendlyfire:
    default: op
  nodewar.command.admin.empire.join:
    default: op
  nodewar.command.admin.empire.leave:
    default: op
  nodewar.command.admin.empire.list:
    default: op
  nodewar.command.admin.player:
    default: op
  nodewar.command.admin.player.*:
    default: false
    children:
      - nodewar.command.admin.player.setempire
      - nodewar.command.admin.player.removeempire
  nodewar.command.admin.player.setempire:
    default: op
  nodewar.command.admin.player.removeempire:
    default: op
  nodewar.command.admin.territory:
    default: op
  nodewar.command.admin.territory.*:
    default: false
    children:
      - nodewar.command.admin.territory.neutralize
      - nodewar.command.admin.territory.setowner
      - nodewar.command.admin.territory.vulnerability
  nodewar.command.admin.territory.neutralize:
    default: op
  nodewar.command.admin.territory.setowner:
    default: op
  nodewar.command.admin.territory.vulnerability:
    default: op
  nodewar.command.empire:
    default: true
  nodewar.command.empire.*:
    default: false
    children:
      - nodewar.command.empire.create
      - nodewar.command.empire.disband
      - nodewar.command.empire.edit
      - nodewar.command.empire.join
      - nodewar.command.empire.leave
      - nodewar.command.empire.list
  nodewar.command.empire.create:
    default: true
  nodewar.command.empire.edit:
    default: true
  nodewar.command.empire.edit.*:
    default: false
    children:
      - nodewar.command.empire.edit.bossbarcolor
      - nodewar.command.empire.edit.color
      - nodewar.command.empire.edit.display
      - nodewar.command.empire.edit.friendlyfire
  nodewar.command.empire.edit.display:
    default: true
  nodewar.command.empire.edit.color:
    default: true
  nodewar.command.empire.edit.bossbarcolor:
    default: true
  nodewar.command.empire.edit.friendlyfire:
    default: true
  nodewar.command.empire.join:
    default: true
  nodewar.command.empire.leave:
    default: true
  nodewar.command.empire.list:
    default: true
  nodewar.command.help:
    default: true