name: Java CI and Maven Package

on:
  release:
    types: [created]
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      # Setup JDK 17 for all jobs (CI and release)
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
          server-id: github  # Required for publishing to GitHub Packages
          settings-path: ${{ github.workspace }} # Path to settings.xml for deployment

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts
      - name: Update dependency graph
        if: github.event_name == 'push' || github.event_name == 'pull_request'
        uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6

      # Publish to GitHub Packages during a release
      - name: Publish to GitHub Packages Apache Maven
        if: github.event_name == 'release'
        run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}